#
# Xenomai Real-Time System
#
# Copyright (c) Siemens AG, 2019 - 2020
#
# Authors:
#  Quirin Gylstorff <quirin.gylstorff@siemens.com>
#
# SPDX-License-Identifier: MIT
#
stages:
  - build
  - lava-test

variables:
  GIT_STRATEGY: clone
  http_proxy: "$HTTP_PROXY"
  https_proxy: "$HTTPS_PROXY"
  ftp_proxy: "$FTP_PROXY"
  no_proxy: "$NO_PROXY"
  XENOMAI_BUILD_OPTION: ":opt-xenomai-next.yml"
  LINUX_BUILD_OPTION: ":opt-linux-latest.yml"
  ISAR_IMAGE: demo-image
  ISAR_DISTRIBUTION: xenomai-demo

default:
  image: kasproject/kas-isar:latest

# add lavacli to the container and install the ssh keys
# for the test infrastructure
.add-lava-ssh-config:
  before_script:
    - mkdir -p -m=700 ~/.ssh
    - echo "ProxyCommand socat - PROXY:$(echo $https_proxy | sed 's|.*://\([^:]*\).*|\1|'):%h:%p,proxyport=$(echo $https_proxy | sed 's|.*:\([0-9]*\)$|\1|')" >> ~/.ssh/config && chmod 600 ~/.ssh/config
    - echo "$LAVA_SSH_UPLOAD_KEY" | tr -d '\r' > ~/.ssh/lava_id_rsa && chmod 600 ~/.ssh/lava_id_rsa
    - echo "$LAVA_SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts

.build:
  extends: .add-lava-ssh-config
  stage: build
  script:
    - kas build kas.yml:board-${TARGET}.yml${XENOMAI_BUILD_OPTION}${LINUX_BUILD_OPTION}${BUILD_OPTIONS}
    - scripts/deploy_for_testing.sh ${TARGET}

.test:
  extends: .add-lava-ssh-config
  stage: lava-test
  script:
    - scripts/install-lavacli.sh
    - scripts/run-lava-tests.sh ${TARGET}
  only:
    variables:
      - $LAVA_SSH_USER


build:qemu-amd64:
  extends: .build
  variables:
    TARGET: qemu-amd64

lava-test:qemu-amd64:
  needs: [ "build:qemu-amd64" ]
  extends: .test
  variables:
    TARGET: qemu-amd64

build:qemu-armhf:
  extends: .build
  variables:
    TARGET: qemu-armhf

lava-test:qemu-armhf:
  needs: [ "build:qemu-armhf" ]
  extends: .test
  variables:
    TARGET: qemu-armhf

build:qemu-arm64:
  extends: .build
  variables:
    TARGET: qemu-arm64

lava-test:qemu-arm64:
  needs: [ "build:qemu-arm64" ]
  extends: .test
  variables:
    TARGET: qemu-arm64

build:board-hikey:
  extends: .build
  variables:
    TARGET: hikey
    BUILD_OPTIONS: ":opt-lava-test.yml"
lava-test:board-hikey:
  needs: [ "build:board-hikey" ]
  extends: .test
  variables:
    TARGET: hikey

build:board-beaglebone:
  extends: .build
  variables:
    TARGET: beagle-bone-black
    BUILD_OPTIONS: ":opt-lava-test.yml"


lava-test:board-beaglebone:
  needs: [ "build:board-beaglebone" ]
  extends: .test
  variables:
    TARGET: beaglebone

build:board-x86-64-efi:
  extends: .build
  variables:
    TARGET: x86-64-efi
    BUILD_OPTIONS: ":opt-lava-test.yml"

lava-test:board-x86-64-efi:
  needs: [ "build:board-x86-64-efi" ]
  extends: .test
  variables:
    TARGET: x86-64

build:board-beaglebone:xenomai-3.0.x:
  extends: .build
  variables:
    TARGET: beagle-bone-black
    XENOMAI_BUILD_OPTION: ":opt-xenomai-3.0.x.yml"
    BUILD_OPTIONS: ":opt-lava-test.yml"
    DEPLOY_DIR_EXTENSION: "xenomai-3.0.x"

lava-test:board-beaglebone:xenomai-3.0.x:
  needs: [ "build:board-beaglebone:xenomai-3.0.x" ]
  extends: .test
  variables:
    TARGET: beaglebone
    DEPLOY_DIR_EXTENSION: "xenomai-3.0.x"

build:board-x86-64-efi:xenomai-3.0.x:
  extends: .build
  variables:
    TARGET: x86-64-efi
    XENOMAI_BUILD_OPTION: ":opt-xenomai-3.0.x.yml"
    BUILD_OPTIONS: ":opt-lava-test.yml"
    DEPLOY_DIR_EXTENSION: "xenomai-3.0.x"

lava-test:board-x86-64-efi:xenomai-3.0.x:
  needs: [ "build:board-x86-64-efi:xenomai-3.0.x" ]
  extends: .test
  variables:
    TARGET: ipc227e
    DEPLOY_DIR_EXTENSION: "xenomai-3.0.x"
