#
# Xenomai Real-Time System
#
# Copyright (c) Siemens AG, 2019 - 2020
#
# Authors:
#  Quirin Gylstorff <quirin.gylstorff@siemens.com>
#
# SPDX-License-Identifier: MIT
#
include:
  - local: '/ci/artifacts.yml'
